version: "3.9"

services:
  postgres:
    build: ./kan_chess_backend/db
    env_file:
      - .env
    ports:
      - "5431:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build: ./kan_chess_backend
    depends_on:
      - postgres
    env_file:
      - .env
    ports:
      - "8080:8080"

  frontend:
    build: ./kan_chess_frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  pgdata:
